[build]
  command = "cd meditationApp_frontend && npm install && npm run build"
  publish = "meditationApp_frontend/dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
